apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springboot
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: 616689340588.dkr.ecr.ap-south-1.amazonaws.com/springboot:latest
        imagePullPolicy: IfNotPresent
        ports:
           - containerPort : 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot
spec:
  type: LoadBalancer
  selector:
    app: spring
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
    
